'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace YokoRODINEXService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="YokoRODINEXService.IYokoRODINEXService")>  _
    Public Interface IYokoRODINEXService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IYokoRODINEXService/CrearPedido", ReplyAction:="http://tempuri.org/IYokoRODINEXService/CrearPedidoResponse")>  _
        Function CrearPedido(ByVal xOrder As System.Xml.Linq.XElement) As System.Xml.Linq.XElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IYokoRODINEXService/CrearPedido", ReplyAction:="http://tempuri.org/IYokoRODINEXService/CrearPedidoResponse")>  _
        Function CrearPedidoAsync(ByVal xOrder As System.Xml.Linq.XElement) As System.Threading.Tasks.Task(Of System.Xml.Linq.XElement)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IYokoRODINEXService/ConsultaStock", ReplyAction:="http://tempuri.org/IYokoRODINEXService/ConsultaStockResponse")>  _
        Function ConsultaStock(ByVal xStock As System.Xml.Linq.XElement) As System.Xml.Linq.XElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IYokoRODINEXService/ConsultaStock", ReplyAction:="http://tempuri.org/IYokoRODINEXService/ConsultaStockResponse")>  _
        Function ConsultaStockAsync(ByVal xStock As System.Xml.Linq.XElement) As System.Threading.Tasks.Task(Of System.Xml.Linq.XElement)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IYokoRODINEXServiceChannel
        Inherits YokoRODINEXService.IYokoRODINEXService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class YokoRODINEXServiceClient
        Inherits System.ServiceModel.ClientBase(Of YokoRODINEXService.IYokoRODINEXService)
        Implements YokoRODINEXService.IYokoRODINEXService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CrearPedido(ByVal xOrder As System.Xml.Linq.XElement) As System.Xml.Linq.XElement Implements YokoRODINEXService.IYokoRODINEXService.CrearPedido
            Return MyBase.Channel.CrearPedido(xOrder)
        End Function
        
        Public Function CrearPedidoAsync(ByVal xOrder As System.Xml.Linq.XElement) As System.Threading.Tasks.Task(Of System.Xml.Linq.XElement) Implements YokoRODINEXService.IYokoRODINEXService.CrearPedidoAsync
            Return MyBase.Channel.CrearPedidoAsync(xOrder)
        End Function
        
        Public Function ConsultaStock(ByVal xStock As System.Xml.Linq.XElement) As System.Xml.Linq.XElement Implements YokoRODINEXService.IYokoRODINEXService.ConsultaStock
            Return MyBase.Channel.ConsultaStock(xStock)
        End Function
        
        Public Function ConsultaStockAsync(ByVal xStock As System.Xml.Linq.XElement) As System.Threading.Tasks.Task(Of System.Xml.Linq.XElement) Implements YokoRODINEXService.IYokoRODINEXService.ConsultaStockAsync
            Return MyBase.Channel.ConsultaStockAsync(xStock)
        End Function
    End Class
End Namespace
